### ISSUE TITLE
installation complete. But can not start successfully.

### ISSUE THREAD

**Issue by gaohang** [fkie-cad/FACT_core#1067]
### The FACT version you are using

master branch 20230701

### Your question

I installed locally successfully. However, when I run ./start_all_installed_fact_components,  I got error prompt as below:

Traceback (most recent call last):
  File "/home/ubuntu/d1t/workspace/FACT_core/src/../start_fact_backend", line 125, in <module>
    FactBackend().main()
  File "/home/ubuntu/d1t/workspace/FACT_core/src/../start_fact_backend", line 87, in main
    self.start()
  File "/home/ubuntu/d1t/workspace/FACT_core/src/../start_fact_backend", line 74, in start
    self.intercom.start()
  File "/home/ubuntu/d1t/workspace/FACT_core/src/intercom/back_end_binding.py", line 45, in start
    InterComBackEndAnalysisPlugInsPublisher(analysis_service=self.analysis_service)
  File "/home/ubuntu/d1t/workspace/FACT_core/src/intercom/back_end_binding.py", line 90, in __init__
    self.publish_available_analysis_plugins(analysis_service)
  File "/home/ubuntu/d1t/workspace/FACT_core/src/intercom/back_end_binding.py", line 94, in publish_available_analysis_plugins
    self.redis.set('analysis_plugins', available_plugin_dictionary)
  File "/home/ubuntu/d1t/workspace/FACT_core/src/storage/redis_interface.py", line 28, in set
    self.redis.set(key, self._split_if_necessary(dumps(value)))
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/redis/commands/core.py", line 2302, in set
    return self.execute_command("SET", *pieces, **options)
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/redis/connection.py", line 1442, in get_connection
    connection.connect()
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/redis/connection.py", line 710, in connect
    self.on_connect()
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/redis/connection.py", line 775, in on_connect
    if str_if_bytes(self.read_response()) != "OK":
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/redis/connection.py", line 865, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/redis/connection.py", line 346, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/home/ubuntu/anaconda3/lib/python3.10/site-packages/redis/connection.py", line 369, in _read_response
    raise error
redis.exceptions.AuthenticationError: Authentication required.
Process ExceptionSafeProcess-115:

**How can I fix it?**

**Comment by gaohang** [comment]
make redis login without need of auth
