### ISSUE TITLE
IP and URI statistic generation crashes if no IP result present in database

### ISSUE THREAD

**Issue by weidenba** [fkie-cad/FACT_core#107]
```
Traceback (most recent call last):
  File "src/update_statistic.py", line 48, in <module>
    sys.exit(main())
  File "src/update_statistic.py", line 38, in main
    updater.update_all_stats()
  File "/home/fact_restricted/git/FACT_core_github/src/statistic/update.py", line 44, in update_all_stats
    self.db.update_statistic('ips_and_uris', self._get_ip_stats())
  File "/home/fact_restricted/git/FACT_core_github/src/statistic/update.py", line 296, in _get_ip_stats
    stats['ips_v4'] = self._get_objects_and_count_of_occurrence_firmware_and_file_db('$processed_analysis.ip_and_uri_finder.ips_v4', unwind=True, sumup_function=sum_up_nested_lists)
  File "/home/fact_restricted/git/FACT_core_github/src/statistic/update.py", line 356, in _get_objects_and_count_of_occurrence_firmware_and_file_db
    combined_result = sum_up_lists(result_firmwares, result_files)
  File "/home/fact_restricted/git/FACT_core_github/src/helperFunctions/merge_generators.py", line 46, in sum_up_lists
    _add_list_to_dict(list_a, tmp)
  File "/home/fact_restricted/git/FACT_core_github/src/helperFunctions/merge_generators.py", line 18, in _add_list_to_dict
    if item[0] in input_dict.keys():
TypeError: unhashable type: 'list'
```

**Comment by weidenba** [comment]
seems to be solved
