### ISSUE TITLE
Server Internal Error on accessing upload page in frontend

### ISSUE THREAD

**Issue by sborpo** [fkie-cad/FACT_core#160]
Hello,
I installed the platform on Ubuntu 16.04,
I ran the  ./start_all_installed_fact_components scripts as mentioned in the readme
When trying access the upload page in the frontend i got a server internal error,
When I looked at the console i saw this execption:
```
[2018-09-26 08:04:42][app][ERROR]: Exception on /upload [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./web_interface/security/decorator.py", line 11, in decorated_view
    return fn(*args, **kwargs)
  File "./web_interface/components/io_routes.py", line 78, in _app_upload
    analysis_plugins = sc.get_available_analysis_plugins()
  File "./intercom/front_end_binding.py", line 34, in get_available_analysis_plugins
    raise Exception("No available plug-ins found. FAF backend might be down!")
```

What my be the problem?
Thanks!

**Comment by dorpvom** [comment]
Hi,
I can't say that I've seen this behavior before. Would you mind starting the fact components individually (./start_fact_db, ./start_fact_backend, ./start_fact_frontend instead ./start_all_installed_fact_components) and dump the backend log for the startup here (anonymized where necessary)?
