### ISSUE TITLE
skip analysis mechanism seems to be broken

### ISSUE THREAD

**Issue by weidenba** [fkie-cad/FACT_core#279]
```sh
Process ExceptionSafeProcess-44:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/weidenba/git/FACT_core/src/helperFunctions/process.py", line 54, in run
    raise exception
  File "/home/weidenba/git/FACT_core/src/helperFunctions/process.py", line 49, in run
    Process.run(self)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/weidenba/git/FACT_core/src/scheduler/Analysis.py", line 187, in scheduler
    self.process_next_analysis(task)
  File "/home/weidenba/git/FACT_core/src/scheduler/Analysis.py", line 198, in process_next_analysis
    self._start_or_skip_analysis(analysis_to_do, fw_object)
  File "/home/weidenba/git/FACT_core/src/scheduler/Analysis.py", line 201, in _start_or_skip_analysis
    if self._analysis_is_already_in_db_and_up_to_date(analysis_to_do, file_object.get_uid()):
  File "/home/weidenba/git/FACT_core/src/scheduler/Analysis.py", line 249, in _analysis_is_already_in_db_and_up_to_date
    if LooseVersion(analysis_plugin_version) < LooseVersion(plugin_version) or \
  File "/usr/lib/python3.6/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/usr/lib/python3.6/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'int' and 'str'

```

**Comment by weidenba** [comment]
Should be fixed for all. Some Databases might be broken now :(
