### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by SMerrony** [fkie-cad/FACT_core#418]
On my Ubuntu 18.04 machine, install.py fails with...

```
[2020-05-20 13:17:40][frontend][INFO]: Initializing docker container for radare
[2020-05-20 13:17:42][frontend][INFO]: Pulling pdf report container
Traceback (most recent call last):
  File "/home/steve/FACT_core/src/install.py", line 177, in <module>
    install()
  File "/home/steve/FACT_core/src/install.py", line 161, in install
    frontend(not args.no_radare, args.nginx)
  File "/home/steve/FACT_core/src/install/frontend.py", line 191, in main
    raise InstallationError('Failed to pull pdf report container:\n{}'.format(output))
helperFunctions.install.InstallationError: Failed to pull pdf report container:
Using default tag: latest
Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39
 
```

**Comment by jstucke** [comment]
I have not encountered this problem yet but other sources suggest setting the environment variable `DOCKER_API_VERSION` to the respective version (i.e. `export DOCKER_API_VERSION=1.39`)

**Comment by SMerrony** [comment]
Thanks.
