### ISSUE TITLE
highlight js installation bug

### ISSUE THREAD

**Issue by jstucke** [fkie-cad/FACT_core#423]
The installation of highlight.js apparently fails because a certificate has expired

```
08:39:27 [2020-06-02 08:39:27][frontend][INFO]: Installing highlight js
08:39:29 Traceback (most recent call last):
08:39:29   File "./src/install.py", line 177, in <module>
08:39:29     install()
08:39:29   File "./src/install.py", line 161, in install
08:39:29     frontend(not args.no_radare, args.nginx)
08:39:29   File "/home/jenkins/workspace/buster/src/install/frontend.py", line 166, in main
08:39:29     _install_css_and_js_files()
08:39:29   File "/home/jenkins/workspace/buster/src/install/frontend.py", line 111, in _install_css_and_js_files
08:39:29     _build_highlight_js()
08:39:29   File "/home/jenkins/workspace/buster/src/install/frontend.py", line 54, in _build_highlight_js
08:39:29     execute_commands_and_raise_on_return_code(commands, error='Failed to set up highlight.js')
08:39:29   File "/home/jenkins/workspace/buster/src/install/frontend.py", line 22, in execute_commands_and_raise_on_return_code
08:39:29     raise InstallationError('Failed to {}\n{}'.format(bad_return, output))
08:39:29 helperFunctions.install.InstallationError: Failed to Failed to set up highlight.js
08:39:29 --2020-06-02 08:39:28--  https://highlightjs.org/download/
08:39:29 Resolving highlightjs.org (highlightjs.org)... 45.79.97.153, 2600:3c01::f03c:92ff:fee7:78b
08:39:29 Connecting to highlightjs.org (highlightjs.org)|45.79.97.153|:443... connected.
08:39:29 ERROR: The certificate of ‘highlightjs.org’ is not trusted.
08:39:29 ERROR: The certificate of ‘highlightjs.org’ has expired.
```

**Comment by jstucke** [comment]
This seems to be caused by the expired root (see CA https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020)
