### ISSUE TITLE
Broken cve database link breaks installation

### ISSUE THREAD

**Issue by dorpvom** [fkie-cad/FACT_core#435]
[CI builds](https://ci.weidenba.de/job/bionic/391) and probably all local installations fail currently due to a broken link in the setup of CVE plugin:

```
18:07:23 [2020-06-26 18:07:23][backend][INFO]: Running ../plugins/analysis/cve_lookup/install.sh
18:07:33 Traceback (most recent call last):
18:07:33   File "./src/install.py", line 177, in <module>
18:07:33     install()
18:07:33   File "./src/install.py", line 165, in install
18:07:33     backend()
18:07:33   File "/home/jenkins/workspace/bionic_external/src/install/backend.py", line 37, in main
18:07:33     _install_plugins()
18:07:33   File "/home/jenkins/workspace/bionic_external/src/install/backend.py", line 101, in _install_plugins
18:07:33     raise InstallationError('Error in installation of {} plugin\n{}'.format(Path(install_script).parent.name, shell_output))
18:07:33 helperFunctions.install.InstallationError: Error in installation of cve_lookup plugin
18:07:33 ------------------------------------
18:07:33    install cve lookup dependencies  
18:07:33 ------------------------------------
18:07:33 Collecting pyxdameraulevenshtein
18:07:33   Downloading pyxDamerauLevenshtein-1.6.tar.gz (59 kB)
18:07:33   Installing build dependencies: started
18:07:33   Installing build dependencies: finished with status 'done'
18:07:33   Getting requirements to build wheel: started
18:07:33   Getting requirements to build wheel: finished with status 'done'
18:07:33     Preparing wheel metadata: started
18:07:33     Preparing wheel metadata: finished with status 'done'
18:07:33 Requirement already satisfied: numpy>=1.16.1 in /usr/local/lib/python3.6/dist-packages (from pyxdameraulevenshtein) (1.19.0)
18:07:33 Building wheels for collected packages: pyxdameraulevenshtein
18:07:33   Building wheel for pyxdameraulevenshtein (PEP 517): started
18:07:33   Building wheel for pyxdameraulevenshtein (PEP 517): finished with status 'done'
18:07:33   Created wheel for pyxdameraulevenshtein: filename=pyxDamerauLevenshtein-1.6-cp36-cp36m-linux_x86_64.whl size=88181 sha256=f9bd3885c0b4158977e6cd8a4afb7a331f6d073bc4978d0d5be4316b9fc89321
18:07:33   Stored in directory: /root/.cache/pip/wheels/bf/4b/14/c4971f1410f7749c271fcc038b6eb659022ec6d7ac7d6bdc15
18:07:33 Successfully built pyxdameraulevenshtein
18:07:33 Installing collected packages: pyxdameraulevenshtein
18:07:33 Successfully installed pyxdameraulevenshtein-1.6
18:07:33 Setting up database
18:07:33 ERROR:root:URLs are invalid. URL format might have been changed or website might have moved.
```

**Comment by dorpvom** [comment]
Seems to have been a temporary issue
