### ISSUE TITLE
install FACT_core failed in Installing cve_lookup plugin.

### ISSUE THREAD

**Issue by sfncat** [fkie-cad/FACT_core#727]
install FACT_core failed in Installing cve_lookup plugin. 
it failed everytime ,I try install on ubuntu 18.04,20.04,both failed.

[2022-01-04 00:50:57][backend][INFO]: Installing cve_lookup plugin.
[2022-01-04 00:54:02][install][ERROR]: Failed to run python3 setup_repository.py:

Traceback (most recent call last):
  File "/opt/FACT_core/src/install.py", line 183, in <module>
    install()
  File "/opt/FACT_core/src/install.py", line 151, in install
    install_fact_components(args, distribution, none_chosen, skip_docker)
  File "/opt/FACT_core/src/install.py", line 171, in install_fact_components
    backend(skip_docker, distribution)
  File "/opt/FACT_core/src/install/backend.py", line 45, in main
    _install_plugins(distribution, skip_docker)
  File "/opt/FACT_core/src/install/backend.py", line 113, in _install_plugins
    plugin_installer.install()
  File "/opt/FACT_core/src/plugins/installer.py", line 29, in install
    self.install_files()
  File "/opt/FACT_core/src/plugins/analysis/cve_lookup/install.py", line 27, in install_files
    run_cmd_with_logging('python3 setup_repository.py')
  File "/opt/FACT_core/src/helperFunctions/install.py", line 222, in run_cmd_with_logging
    raise err
  File "/opt/FACT_core/src/helperFunctions/install.py", line 216, in run_cmd_with_logging
    subprocess.run(cmd_, stdout=PIPE, stderr=PIPE, encoding='UTF-8', shell=shell, check=True, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', 'setup_repository.py']' died with <Signals.SIGKILL: 9>.

**Comment by sfncat** [comment]
sloved.
the vm memory is too small.
