### ISSUE TITLE
Wondering where this error message appear.Backend did not start. Shutting down

### ISSUE THREAD

**Issue by redghostplus** [fkie-cad/FACT_core#927]
I just successfully executed install.py. I happily reboot and open the program with anticipation. Then I found the following message when I opened the file, the program does not appear to have opened successfully.Not sure if I'm missing something?

[2022-12-09 16:16:46][start_all_installed_fact_components][INFO]: starting db
[2022-12-09 16:16:47][MongoMgr][INFO]: start local mongo database
Traceback (most recent call last):
  File "/home/redghost/RedPlus/tools/FACT_core/src/../start_fact_db", line 48, in <module>
    work_load_stat = WorkLoadStatistic(config=config, component='database')
  File "/home/redghost/RedPlus/tools/FACT_core/src/statistic/work_load.py", line 21, in __init__
    self.db = StatisticDbUpdater(config=self.config)
  File "/home/redghost/RedPlus/tools/FACT_core/src/storage/db_interface_statistic.py", line 13, in __init__
    super().__init__(config=config)
  File "/home/redghost/RedPlus/tools/FACT_core/src/storage/mongo_interface.py", line 25, in __init__
    self._authenticate()
  File "/home/redghost/RedPlus/tools/FACT_core/src/storage/mongo_interface.py", line 40, in _authenticate
    self.client.admin.authenticate(user, pw, mechanism='SCRAM-SHA-1')
  File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 3207, in __call__
    raise TypeError(
TypeError: 'Collection' object is not callable. If you meant to call the 'authenticate' method on a 'Database' object it is failing because no such method exists.
[2022-12-09 16:16:48][start_all_installed_fact_components][INFO]: starting frontend
[2022-12-09 16:16:48][start_all_installed_fact_components][INFO]: starting backend
Traceback (most recent call last):
  File "/home/redghost/RedPlus/tools/FACT_core/src/../start_fact_backend", line 25, in <module>
    from analysis.PluginBase import PluginInitException
  File "/home/redghost/RedPlus/tools/FACT_core/src/analysis/PluginBase.py", line 10, in <module>
    from objects.file import FileObject
  File "/home/redghost/RedPlus/tools/FACT_core/src/objects/file.py", line 8, in <module>
    from helperFunctions.hash import get_sha256
  File "/home/redghost/RedPlus/tools/FACT_core/src/helperFunctions/hash.py", line 8, in <module>
    import tlsh
ModuleNotFoundError: No module named 'tlsh'
Traceback (most recent call last):
  File "/home/redghost/RedPlus/tools/FACT_core/src/../start_fact_frontend", line 82, in <module>
    work_load_stat = WorkLoadStatistic(config=CONFIG, component='frontend')
  File "/home/redghost/RedPlus/tools/FACT_core/src/statistic/work_load.py", line 21, in __init__
    self.db = StatisticDbUpdater(config=self.config)
  File "/home/redghost/RedPlus/tools/FACT_core/src/storage/db_interface_statistic.py", line 13, in __init__
    super().__init__(config=config)
  File "/home/redghost/RedPlus/tools/FACT_core/src/storage/mongo_interface.py", line 25, in __init__
    self._authenticate()
  File "/home/redghost/RedPlus/tools/FACT_core/src/storage/mongo_interface.py", line 40, in _authenticate
    self.client.admin.authenticate(user, pw, mechanism='SCRAM-SHA-1')
  File "/usr/local/lib/python3.9/site-packages/pymongo/collection.py", line 3207, in __call__
    raise TypeError(
TypeError: 'Collection' object is not callable. If you meant to call the 'authenticate' method on a 'Database' object it is failing because no such method exists.
[2022-12-09 16:16:50][start_all_installed_fact_components][CRITICAL]: Backend did not start. Shutting down...

**Comment by redghostplus** [comment]
Thanks for your reply. I tried to upgrade but couldn't complete it. Later decided to simply reinstall the new version, but got the following error.

[2022-12-12 15:47:20][install][INFO]: FACT Installer 1.2
[2022-12-12 15:47:20][common][INFO]: Updating system
[2022-12-12 15:47:24][common][WARNING]: FACT is not set up using git. Note that *adding submodules* won't work!!
[2022-12-12 15:47:24][install][INFO]: Installing apt-transport-https autoconf automake build-essential git libtool python3 python3-dev unzip libfuzzy-dev libmagic-dev
[2022-12-12 15:47:26][common][INFO]: Installing python3 pip
[2022-12-12 15:48:27][install][INFO]: Installing nodejs
[2022-12-12 15:49:04][frontend][INFO]: Creating directory for authentication
[2022-12-12 15:49:04][frontend][INFO]: Initializing docker container for radare
[2022-12-12 15:49:06][frontend][INFO]: Pulling pdf report container
psql (PostgreSQL) 10.22 (Ubuntu 10.22-0ubuntu0.18.04.1)
[2022-12-12 15:49:08][db][INFO]: Skipping PostgreSQL installation. Reason: Already installed.
[2022-12-12 15:49:08][db][INFO]: Initializing PostgreSQL database
[2022-12-12 15:49:09][install][INFO]: Installing libjpeg-dev libssl-dev redis binutils file openssl bison flex pkg-config
[2022-12-12 15:49:32][backend][INFO]: Installing yara v4.2.3
[2022-12-12 15:49:57][backend][INFO]: Installing checksec.sh
[2022-12-12 15:49:58][backend][INFO]: Pulling fact extraction container
[2022-12-12 15:50:01][backend][INFO]: Installing cwe_checker plugin.
[2022-12-12 15:50:03][backend][INFO]: Finished installing cwe_checker plugin.

[2022-12-12 15:50:03][backend][INFO]: Installing ip_and_uri_finder plugin.
[2022-12-12 15:50:13][backend][INFO]: Finished installing ip_and_uri_finder plugin.

[2022-12-12 15:50:13][backend][INFO]: Installing cve_lookup plugin.
[2022-12-12 15:51:37][backend][INFO]: Finished installing cve_lookup plugin.

[2022-12-12 15:51:37][backend][INFO]: Installing device_tree plugin.
[2022-12-12 15:51:42][backend][INFO]: Finished installing device_tree plugin.

[2022-12-12 15:51:42][backend][INFO]: Installing software_components plugin.
[2022-12-12 15:51:42][backend][INFO]: Finished installing software_components plugin.

[2022-12-12 15:51:42][backend][INFO]: Installing binwalk plugin.
[2022-12-12 15:52:11][install][ERROR]: Failed to run sudo -EH pip3 install -U .:
Processing /home/redghost/RedPlus/tools/FACT/src/plugins/analysis/binwalk/build/binwalk-2.3.3
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: binwalk
  Building wheel for binwalk (setup.py): started
  Building wheel for binwalk (setup.py): finished with status 'done'
  Created wheel for binwalk: filename=binwalk-2.3.3-py3-none-any.whl size=135275 sha256=155e14a626443cbddeca953837e0c6f887864dc882b9cc5e56666c01032ac502
  Stored in directory: /root/.cache/pip/wheels/6f/c5/53/cb6afd39bb1d81a9e602b1fb468546602cd8f7cd8751d0668b
Successfully built binwalk
Installing collected packages: binwalk
  Attempting uninstall: binwalk
    Found existing installation: binwalk 2.2.0.post1534001
ERROR: Cannot uninstall 'binwalk'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Traceback (most recent call last):
  File "/home/redghost/RedPlus/tools/FACT/src/./install.py", line 214, in <module>
    install()
  File "/home/redghost/RedPlus/tools/FACT/src/./install.py", line 182, in install
    install_fact_components(args, distribution, none_chosen, skip_docker)
  File "/home/redghost/RedPlus/tools/FACT/src/./install.py", line 202, in install_fact_components
    backend(skip_docker, distribution)
  File "/home/redghost/RedPlus/tools/FACT/src/install/backend.py", line 48, in main
    _install_plugins(distribution, skip_docker)
  File "/home/redghost/RedPlus/tools/FACT/src/install/backend.py", line 117, in _install_plugins
    plugin_installer.install()
  File "/home/redghost/RedPlus/tools/FACT/src/plugins/installer.py", line 40, in install
    self.build()
  File "/home/redghost/RedPlus/tools/FACT/src/plugins/analysis/binwalk/install.py", line 37, in build
    run_cmd_with_logging('sudo -EH pip3 install -U .')
  File "/home/redghost/RedPlus/tools/FACT/src/helperFunctions/install.py", line 219, in run_cmd_with_logging
    raise err
  File "/home/redghost/RedPlus/tools/FACT/src/helperFunctions/install.py", line 213, in run_cmd_with_logging
    subprocess.run(cmd_, stdout=PIPE, stderr=STDOUT, encoding='UTF-8', shell=shell, check=True, **kwargs)
  File "/usr/local/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo', '-EH', 'pip3', 'install', '-U', '.']' returned non-zero exit status 1.
