### ISSUE TITLE
Installing binwalk plugin returned non-zero exit status 1

### ISSUE THREAD

**Issue by redghostplus** [fkie-cad/FACT_core#930]
I get the following error when I try to perform the installation. I don't know if it is related to the fact that I have already installed binwalk?

[2022-12-12 15:47:20][install][INFO]: FACT Installer 1.2
[2022-12-12 15:47:20][common][INFO]: Updating system
[2022-12-12 15:47:24][common][WARNING]: FACT is not set up using git. Note that adding submodules won't work!!
[2022-12-12 15:47:24][install][INFO]: Installing apt-transport-https autoconf automake build-essential git libtool python3 python3-dev unzip libfuzzy-dev libmagic-dev
[2022-12-12 15:47:26][common][INFO]: Installing python3 pip
[2022-12-12 15:48:27][install][INFO]: Installing nodejs
[2022-12-12 15:49:04][frontend][INFO]: Creating directory for authentication
[2022-12-12 15:49:04][frontend][INFO]: Initializing docker container for radare
[2022-12-12 15:49:06][frontend][INFO]: Pulling pdf report container
psql (PostgreSQL) 10.22 (Ubuntu 10.22-0ubuntu0.18.04.1)
[2022-12-12 15:49:08][db][INFO]: Skipping PostgreSQL installation. Reason: Already installed.
[2022-12-12 15:49:08][db][INFO]: Initializing PostgreSQL database
[2022-12-12 15:49:09][install][INFO]: Installing libjpeg-dev libssl-dev redis binutils file openssl bison flex pkg-config
[2022-12-12 15:49:32][backend][INFO]: Installing yara v4.2.3
[2022-12-12 15:49:57][backend][INFO]: Installing checksec.sh
[2022-12-12 15:49:58][backend][INFO]: Pulling fact extraction container
[2022-12-12 15:50:01][backend][INFO]: Installing cwe_checker plugin.
[2022-12-12 15:50:03][backend][INFO]: Finished installing cwe_checker plugin.

[2022-12-12 15:50:03][backend][INFO]: Installing ip_and_uri_finder plugin.
[2022-12-12 15:50:13][backend][INFO]: Finished installing ip_and_uri_finder plugin.

[2022-12-12 15:50:13][backend][INFO]: Installing cve_lookup plugin.
[2022-12-12 15:51:37][backend][INFO]: Finished installing cve_lookup plugin.

[2022-12-12 15:51:37][backend][INFO]: Installing device_tree plugin.
[2022-12-12 15:51:42][backend][INFO]: Finished installing device_tree plugin.

[2022-12-12 15:51:42][backend][INFO]: Installing software_components plugin.
[2022-12-12 15:51:42][backend][INFO]: Finished installing software_components plugin.

[2022-12-12 15:51:42][backend][INFO]: Installing binwalk plugin.
[2022-12-12 15:52:11][install][ERROR]: Failed to run sudo -EH pip3 install -U .:
Processing /home/redghost/RedPlus/tools/FACT/src/plugins/analysis/binwalk/build/binwalk-2.3.3
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: binwalk
Building wheel for binwalk (setup.py): started
Building wheel for binwalk (setup.py): finished with status 'done'
Created wheel for binwalk: filename=binwalk-2.3.3-py3-none-any.whl size=135275 sha256=155e14a626443cbddeca953837e0c6f887864dc882b9cc5e56666c01032ac502
Stored in directory: /root/.cache/pip/wheels/6f/c5/53/cb6afd39bb1d81a9e602b1fb468546602cd8f7cd8751d0668b
Successfully built binwalk
Installing collected packages: binwalk
Attempting uninstall: binwalk
Found existing installation: binwalk 2.2.0.post1534001
ERROR: Cannot uninstall 'binwalk'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Traceback (most recent call last):
File "/home/redghost/RedPlus/tools/FACT/src/./install.py", line 214, in
install()
File "/home/redghost/RedPlus/tools/FACT/src/./install.py", line 182, in install
install_fact_components(args, distribution, none_chosen, skip_docker)
File "/home/redghost/RedPlus/tools/FACT/src/./install.py", line 202, in install_fact_components
backend(skip_docker, distribution)
File "/home/redghost/RedPlus/tools/FACT/src/install/backend.py", line 48, in main
_install_plugins(distribution, skip_docker)
File "/home/redghost/RedPlus/tools/FACT/src/install/backend.py", line 117, in install_plugins
plugin_installer.install()
File "/home/redghost/RedPlus/tools/FACT/src/plugins/installer.py", line 40, in install
self.build()
File "/home/redghost/RedPlus/tools/FACT/src/plugins/analysis/binwalk/install.py", line 37, in build
run_cmd_with_logging('sudo -EH pip3 install -U .')
File "/home/redghost/RedPlus/tools/FACT/src/helperFunctions/install.py", line 219, in run_cmd_with_logging
raise err
File "/home/redghost/RedPlus/tools/FACT/src/helperFunctions/install.py", line 213, in run_cmd_with_logging
subprocess.run(cmd, stdout=PIPE, stderr=STDOUT, encoding='UTF-8', shell=shell, check=True, **kwargs)
File "/usr/local/lib/python3.9/subprocess.py", line 524, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo', '-EH', 'pip3', 'install', '-U', '.']' returned non-zero exit status 1.

**Comment by jstucke** [comment]
> ERROR: Cannot uninstall 'binwalk'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

The problem is the following: you can either install python packages using the package manager of your distribution (e.g. apt) or install them using pip. But if a package is installed via your system's package manager, pip can not uninstall / update it. 

There is an easy solution, though: Using a virtual environment. Could you please create a "venv" and run the installation again? (see [here](https://docs.python.org/3/tutorial/venv.html) for documentation on virtual environments)
